### ISSUE TITLE
Ruby setup instructions missing `bundle install`

### ISSUE THREAD

**Issue by meeas** [asciidoctor/asciidoctor-reveal.js#469] opened 2022-06-01 03:23 UTC
It has `bundle config` and `bundle binstubs` but never says to do a `bundle install`.

I'm new to ruby, so I may be missing something, but I had to issue a bundle install in Fedora.

**Comment by mojavelinux** [comment] 2022-06-01 07:48
You are correct that there is a command absent. It appears that the problem is the fix needs to be backported to the branch from which the docs are built as the change has already been made to the default branch.

See https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/docs/modules/setup/pages/ruby-setup.adoc

**Comment by mojavelinux** [comment] 2022-06-01 08:04
I've submitted a PR to improve the setup guide in the default branch. See #470. Once that is reviewed and merged, we can backport the whole file to the maint-4.1.x branch so it gets published on docs.asciidoctor.org.

**Comment by Mogztter** [comment] 2022-06-03 12:40
fixed in [0d0197a](https://github.com/asciidoctor/asciidoctor-reveal.js/commit/0d0197a8394e35516ebdc29447d9fae5925d0120)

**Closed by Mogztter** 2022-06-03 12:40 UTC
