### ISSUE TITLE
Slim & jade templates are not aligned

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor-reveal.js#91] opened 2016-09-06 08:05 UTC
There are many differences between the slim & jade templates. Here is a diff realized by comparing the template document 
![screenshot 2016-09-06 08 56 44](https://cloud.githubusercontent.com/assets/463790/18264358/12147782-7410-11e6-8afd-e8058dc82d36.png)

Tasks to be done :  

- [ ] Compare the templates & prepare a report of the differences
- [ ] Update jade for the differences observed

**Comment by obilodeau** [comment] 2016-09-06 13:17
This is a duplicate of #63. I will close it. Once slim/jade are on par with each other then we can open individual issues on differences but right now this will just create too many issues.

**Closed by obilodeau** 2016-09-06 13:17 UTC
Labels: jade
