### ISSUE TITLE
Highlightjs for Haskell looks bad/different in revealjs

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/asciidoctor-reveal.js#527] opened 2024-02-20 08:30 UTC
Here is a simple code for problem demonstration:
```
= Oh, this pesky state...
:data-uri:
:revealjsdir: reveal.js
:backend: revealjs
:source-highlighter: highlightjs
:highlightjs-languages: haskell, asciidoc

== Stateless example

[source, Haskell, linenums]
----
  myInts :: [Int]
  myInts = [1, 42, 1, 42, 1, 42]

  doubled :: [Int]
  doubled = map (\int -> int * 2) myInts
----

[source, haskell, linenums]
----
-- Not polymorphic list reversion.
reverselist [Int] -> [Int]
reverseList list = ...

-- Polymorphic list reversion.
reverselist [a] -> [a]
reverseList list = ...
----
```

Here how it looks with plain Asciidoctor:
![image](https://github.com/asciidoctor/asciidoctor-reveal.js/assets/2750775/f9f1c939-e2c7-4c43-bcc9-a42b750b05a8)

And here how it looks with Asciidoctor+RevealJS:
![image](https://github.com/asciidoctor/asciidoctor-reveal.js/assets/2750775/3568cfbf-56ca-40c2-a6ad-0da95c5fe257)

The plain Asciidoctor highlighting looks way better.
Might it be that I found an issue in Asciidoctor+RevaelJS?

**Comment by refaelsh** [comment] 2024-02-20 08:40
UPDATE:
I just found out by accident that if I remove the line `-- Not polymorphic list reversion.` from the source code block, the problem goes away. It seems to be that only when commented lines appear in a Haskell source code block, then the problems begin.

**Comment by ggrossetie** [comment] 2024-02-24 12:03
As far as I remember, reveal.js is using its own plugin to do syntax highlighting. That's the reason why you can have differences between Asciidoctor using Highlight.js or Rouge and Asciidoctor reveal.js.

If you can reproduce this issue using the latest version of reveal.js you should open an issue there: https://github.com/hakimel/reveal.js

I'm closing since I don't think we should fix this issue here.

**Closed by ggrossetie** 2024-02-24 12:03 UTC

**Comment by refaelsh** [comment] 2024-02-25 07:16
Oh, yes, I understand. Thank you very much for the prompt response.

> If you can reproduce this issue using the latest version of reveal.js

I will try it and go open a bug there.
