### ISSUE TITLE
some reveal options with camelcase name don't work

### ISSUE THREAD

**Issue by websectrainer** [asciidoctor/asciidoctor-reveal.js#251] opened 2019-03-16 18:29 UTC
Some options with caps in their name won't work.
For example (NB : there are others affected options ) : 
```
:revealjs_fragmentInURL:
:revealjs_showNotes:
```
They won't change the corresponding option in generated presentation javascript in `Reveal.initialize(` part.

I've tracked down the issue down to the converter.rb file : options noted in camelCase in this file don't work, whereas option with no caps do.
`_buf << ((to_boolean(attr 'revealjs_fragmentInURL', false)).to_s);`
is broken, while
`_buf << ((to_boolean(attr 'revealjs_fragmentinurl', false)).to_s);`
works, and is case insensitive (both :revealjs_fragmentInURL: and :revealjs_fragmentinurl: would work).

To illustrate further : showslidenumber and slidenumber work, because they are in minuscules in this file.

Besides, thanx a lot for the 2.0 update :-)

**Comment by mojavelinux** [comment] 2019-03-16 18:34
This is likely due to this issue/behavior: https://github.com/asciidoctor/asciidoctor/issues/509

**Comment by themr0c** [comment] 2019-03-18 10:28
I can confirm the issue with  :revealjs_parallaxBackgroundImage: and :revealjs_parallaxBackgroundSize:.

I guess the attributes are turned into lowercase before passing in the converter.

As a quickfix, I got things working by converting the strings in lowercase in `converter.rb`.

I found the mixup of snakecase and camelcase quite confusing. I must confess I didn't see the benefits of case sensitivity in this particular usecase.

**Comment by mojavelinux** [comment] 2019-06-08 07:17
This has been reported again in #263.

> As a quickfix, I got things working by converting the strings in lowercase in converter.rb.

That's the real fix that needs to happen.

**Comment by mojavelinux** [comment] 2019-06-08 07:20
@themr0c @akosma If you'd like to submit a PR, it's just a matter of making all the attribute name references lowercase (e.g., `attr 'revealjs_backgroundTransition', 'fade'`). Here's the file that needs to be updated: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/document.html.slim (Note that converter.rb is generated).

**Comment by bentolor** [comment] 2019-06-26 11:03
Trying to fix this in #267

**Comment by obilodeau** [comment] 2019-12-04 06:43
Merged @bentolor's fix. It was just released in 2.0.1. Can you confirm that the fixed version works for you?

**Comment by obilodeau** [comment] 2020-01-11 20:51
Closing. Feel free to re-open if required.

**Closed by obilodeau** 2020-01-11 20:51 UTC
