### ISSUE TITLE
revealjs_backgroundTransition attribute has no effect

### ISSUE THREAD

**Issue by akosma** [asciidoctor/asciidoctor-reveal.js#263] opened 2019-06-05 11:26 UTC
The following Asciidoc file contains a `revealjs_backgroundTransition` attribute, yet the generated HTML does output `backgroundTransition: 'fade'` in the configuration instead.

```asciidoc
:revealjs_theme: white
:revealjs_backgroundTransition: none

= White

Title

[background-color="black"]
== Black

TIP: This is a tip

== White

White slide
```

Built with the simplest possible command: `asciidoctor-revealjs slides.adoc` using the following software versions:

```
$ asciidoctor-revealjs --version
Asciidoctor 2.0.9 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

The source Asciidoc and generated HTML are attached: [slides.zip](https://github.com/asciidoctor/asciidoctor-reveal.js/files/3256912/slides.zip)

**Comment by mojavelinux** [comment] 2019-06-08 07:11
That's because of this issue: https://github.com/asciidoctor/asciidoctor/issues/509

In brief, attributes cannot contain uppercase characters. You can write them that way, but the AsciiDoc processor forces them to lowercase. Therefore, the code needs to be changed so that it looks for `revealjs_backgroundtransition` not `revealjs_backgroundTransition`. (That way, you can write it however you want and it will still work).

**Comment by mojavelinux** [comment] 2019-06-08 07:14
Btw, there are a number of settings that are affected by this:

* revealjs_controlsTutorial
* revealjs_controlsLayout
* revealjs_controlsBackArrows
* revealjs_fragmentInURL
* revealjs_showNotes
* revealjs_autoPlayMedia
* revealjs_autoSlide
* revealjs_autoSlideStoppable
* revealjs_autoSlideMethod
* revealjs_defaultTiming
* revealjs_mouseWheel
* revealjs_hideAddressBar
* revealjs_previewLinks
* revealjs_transitionSpeed
* revealjs_backgroundTransition
* revealjs_viewDistance
* revealjs_parallaxBackgroundImage
* revealjs_parallaxBackgroundSize
* revealjs_parallaxBackgroundHorizontal
* revealjs_parallaxBackgroundVertical

None of those are going to work as the code stands now.

**Comment by mojavelinux** [comment] 2019-06-08 07:16
Here's where this happens in core: https://github.com/asciidoctor/asciidoctor/blob/35c1f9a8f7c1cee310d6c1d1ad46ec5ae4702d54/lib/asciidoctor/parser.rb#L2118 and https://github.com/asciidoctor/asciidoctor/blob/35c1f9a8f7c1cee310d6c1d1ad46ec5ae4702d54/lib/asciidoctor/parser.rb#L2731-L2749

**Comment by bentolor** [comment] 2019-06-26 10:26
I'm currently desperately trying to get my presentation finished and this bug made me heavy headaches. Many attributes are silently failing and I was totally puzzled unless I noted that it was always attributes with casing in in and I remembered that Github issue I saw some time ago…

@mojavelinux I'm unsure which way to go:

* should I open a MR changing all asciidoctor attribute refs to purely lowercase or would this be wrong?
* or should the code somewhere start using the referred `sanitize_attribute_name` which IMHO would fix that problem?

**Comment by mojavelinux** [comment] 2019-06-26 10:32
I would go with the first option. Case doesn't mean anything in AsciiDoc attributes, so there's never any reason to use it.

If you submitted a PR, I would expect it could get merged quickly because this feature is broken as it stands.

**Comment by bentolor** [comment] 2019-06-26 10:53
Thanks for the lightning-fast reply! I opened #267

**Comment by bentolor** [comment] 2019-06-26 10:54
P.S. I'm using my local patched version for now, so I'm good for now. No release pressure…

**Comment by obilodeau** [comment] 2019-12-04 06:40
This was fixed with the just-released 2.0.1. Can you confirm that the fixed version works for you?

**Comment by obilodeau** [comment] 2019-12-20 04:55
Closing. This was confirmed elsewhere as fixed. Feel free to re-open.

**Closed by obilodeau** 2019-12-20 04:55 UTC

**Comment by akosma** [comment] 2019-12-20 10:17
I confirm it works perfectly well now. Thanks a lot!
