### ISSUE TITLE
Document that speaker notes will be displayed as plain-text when using a CDN (jsDeliver in particular)

### ISSUE THREAD

**Issue by korve** [asciidoctor/asciidoctor-reveal.js#500] opened 2023-05-12 04:51 UTC
When i press `s` inside a reveal.js presentation the speaker view pops up. In this view the  HTML is displayed as plain text and not rendered at all (See screenshot). The problem here seems to be that the CDN delivers the content as plain/text.

Versions:
```
Asciidoctor reveal.js 4.1.0 using Asciidoctor 2.0.18 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

![Screenshot 2023-05-12 at 06 50 04](https://github.com/hakimel/reveal.js/assets/4459994/c7663876-5d20-4328-9dd7-437982749521)

**Comment by ggrossetie** [comment] 2023-05-12 07:42
Hey @korve this is a duplicate of https://github.com/asciidoctor/asciidoctor-reveal.js/issues/414

> jsDeliver states that "serving HTML pages is not supported for security reasons". So you'd have to use a different CDN or publish through a hosting platform such as GitHub Pages, GitLab Pages, Netlify, etc.

**Comment by ggrossetie** [comment] 2023-05-12 07:43
Feel free to submit a pull request to add a note in the documentation.

**Comment by refaelsh** [comment] 2023-06-11 11:17
@korve Do you have the following line in your adoc file:
```
:revealjsdir: https://cdn.jsdelivr.net/npm/reveal.js@3.9.2
```
Or something to that effect?

**Comment by ggrossetie** [comment] 2023-06-11 12:39
I've updated the title.
This is not a bug, it's a limitation of jsDeliver for security reasons. Speaker notes will be displayed as plain-text when using jsDeliver. If you want to use speaker notes, you will need to use a self-hosted (or local) copy of reveal.js.

**Comment by refaelsh** [comment] 2023-06-11 14:57
> Feel free to submit a pull request to add a note in the documentation.

I will try it.

**Closed** 2023-06-17 23:23 UTC
Labels: :memo: documentation
