### ISSUE TITLE
Error trying to install using yarn

### ISSUE THREAD

**Issue by iwfmp** [asciidoctor/asciidoctor-reveal.js#128] opened 2017-05-01 15:49 UTC
error reveal.js@3.3.0: The engine "node" is incompatible with this module. Expected version "~4.1.1".
error Found incompatible module

Installing reveal.js through yarn works just fine...

**Comment by obilodeau** [comment] 2017-05-01 18:36
What version of reveal.js does Yarn install when trying to install directly? Something regarding node version required seems to have changed in upstream's reveal.js' code which happened after 3.4.0 and now.

* https://github.com/hakimel/reveal.js/pull/1760
* https://github.com/hakimel/reveal.js/commit/2bd6b563be65bb0ff95593b30572ca72fd3e8b77

I'm not familiar with yarn, can you give me the steps so I can reproduce your problem on my system? My package manager tells me I could run yarn version: 0.23.3.

**Comment by iwfmp** [comment] 2017-05-01 18:46
yarn 0.23 is the latest AFAIK.
Pretty similar to npm, albeit a small difference in command name

run
`yarn add --dev reveal.js`

And it installed reveal.js version 3.4.1

**Comment by Mogztter** [comment] 2019-12-09 22:02
> error reveal.js@3.3.0: The engine "node" is incompatible with this module. Expected version "~4.1.1".
error Found incompatible module

I think you were using an outdated version of Node right?
We should probably close this issue since the install procedure has changed.

@iwfmp Feel free to open a new issue if you still have troubles installing this package.

**Closed** 2019-12-10 05:23 UTC
Labels: help wanted
